### ISSUE TITLE
[♻️ REFACTOR] PathVariable로 customerId/ownerId인자를 받는 부분 제거

### ISSUE THREAD

**Issue by onda0-0** [nbc-team-gumi/goodbite-main#121]
## 💬 설명
- 현재 PathVariable로 customer 인자를 받는 방식을 제거
- 관련된 검증 부분도 함께 제거

## ☑️TO-DO
- [ ]  PathVariable로 customerId 인자를 받는 부분 코드 수정
- [ ]  관련 검증 로직 제거
- [ ]  PathVariable로 ownerId 인자를 받는 부분 코드 수정
- [ ]  관련 검증 로직 제거
