### ISSUE TITLE
[📖SCRIPT] CI/CD 스크립트 추가

### ISSUE THREAD

**Issue by a-white-bit** [nbc-team-gumi/goodbite-main#278]
## 💬 설명

GitHub Actions 스크립트 관련 작업

## ☑️TO-DO

- [ ] 자동 린팅 기능
- [ ] 슬랙으로 로그 발송 기능
- [ ] 다중 서버 배포
